[package]
name = "rs_tfhe"
version = "0.1.0"
authors = ["Naoki Matsumoto <m.naoki9911@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fftw = {version = "0.6.2"}
rand = "0.7.3"
rand_distr = "0.3.0"